contact_links:
  - name: Discussion Q&A
    url: https://github.com/aspl-lang/aspl/discussions/categories/q-a
    about: You can ask and answer questions here
  - name: Discord
    url: https://discord.gg/UUNzAFrKU2
    about: You can ask and answer questions here
